source 'https://rubygems.org'

ruby '3.2.2'

# Core
gem 'rails', '~> 7.1.0'
gem 'puma', '~> 6.0'

# Database
gem 'mongoid', '~> 8.1'

# API
gem 'rack-cors', '~> 2.0'
gem 'active_model_serializers', '~> 0.10.13'

# File Upload
gem 'cloudinary', '~> 1.27'

# Service Communication
gem 'httparty', '~> 0.21'

# Background Jobs
gem 'sidekiq', '~> 7.0'
gem 'redis', '~> 5.0'

# Monitoring & Logging
gem 'newrelic_rpm', '~> 9.0'
gem 'sentry-ruby', '~> 5.8'
gem 'sentry-rails', '~> 5.8'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.0'
  gem 'database_cleaner-mongoid', '~> 2.0'
  gem 'rubocop', '~> 1.50', require: false
  gem 'rubocop-rails', '~> 2.19', require: false
  gem 'brakeman', '~> 5.4', require: false
  gem 'bundler-audit', '~> 0.9', require: false
end

group :development do
  gem 'listen', '~> 3.8'
  gem 'spring', '~> 4.1'
  gem 'spring-watcher-listen', '~> 2.1'
end

group :test do
  gem 'shoulda-matchers', '~> 5.3'
  gem 'simplecov', '~> 0.22', require: false
  gem 'webmock', '~> 3.18'
  gem 'vcr', '~> 6.1'
end 