import { addIcons } from 'ionicons';
import { 
  notificationsOutline,
  chatbubblesOutline,
  cameraOutline,
  imageOutline,
  trashOutline,
  closeOutline,
  checkmarkOutline,
  alertOutline,
  warningOutline,
  informationOutline,
  menuOutline,
  personOutline,
  logOutOutline,
  homeOutline,
  documentTextOutline,
  settingsOutline,
  addOutline,
  createOutline,
  searchOutline,
  filterOutline,
  arrowBackOutline,
  arrowForwardOutline,
  businessOutline,
  gridOutline,
  calendarOutline,
  peopleOutline,
  add,
  timeOutline,
  walletOutline,
  personCircleOutline,
  chevronForwardOutline,
  chevronBackOutline,
  ellipsisVerticalOutline,
  locationOutline,
  mailOutline,
  callOutline,
  lockClosedOutline,
  eyeOutline,
  eyeOffOutline,
  barChartOutline,
  briefcaseOutline,
  warning,
  chatbubbles,
  location
} from 'ionicons/icons';

export function registerIcons() {
  addIcons({
    'notifications-outline': notificationsOutline,
    'chatbubbles-outline': chatbubblesOutline,
    'camera-outline': cameraOutline,
    'image-outline': imageOutline,
    'trash-outline': trashOutline,
    'close-outline': closeOutline,
    'checkmark-outline': checkmarkOutline,
    'alert-outline': alertOutline,
    'warning-outline': warningOutline,
    'information-outline': informationOutline,
    'menu-outline': menuOutline,
    'person-outline': personOutline,
    'log-out-outline': logOutOutline,
    'home-outline': homeOutline,
    'document-text-outline': documentTextOutline,
    'settings-outline': settingsOutline,
    'add-outline': addOutline,
    'create-outline': createOutline,
    'search-outline': searchOutline,
    'filter-outline': filterOutline,
    'arrow-back-outline': arrowBackOutline,
    'arrow-forward-outline': arrowForwardOutline,
    'business-outline': businessOutline,
    'grid-outline': gridOutline,
    'calendar-outline': calendarOutline,
    'people-outline': peopleOutline,
    'add': add,
    'time-outline': timeOutline,
    'wallet-outline': walletOutline,
    'person-circle-outline': personCircleOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'chevron-back-outline': chevronBackOutline,
    'ellipsis-vertical-outline': ellipsisVerticalOutline,
    'location-outline': locationOutline,
    'mail-outline': mailOutline,
    'call-outline': callOutline,
    'lock-closed-outline': lockClosedOutline,
    'eye-outline': eyeOutline,
    'eye-off-outline': eyeOffOutline,
    'bar-chart-outline': barChartOutline,
    'briefcase-outline': briefcaseOutline,
    'warning': warning,
    'chatbubbles': chatbubbles,
    'location': location
  });
} 