common: &default_settings
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  app_name: <%= ENV['NEW_RELIC_APP_NAME'] || 'odc-shift-service' %>
  distributed_tracing:
    enabled: true
  
  # Log level for the New Relic agent
  log_level: info

  # Your application environment
  monitor_mode: true
  
  # Enable browser monitoring
  browser_monitoring:
    auto_instrument: false

development:
  <<: *default_settings
  app_name: <%= ENV['NEW_RELIC_APP_NAME'] || 'odc-shift-service' %> (Development)
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: <%= ENV['NEW_RELIC_APP_NAME'] || 'odc-shift-service' %> (Staging)
  monitor_mode: true

production:
  <<: *default_settings
  monitor_mode: true
  
  # Increase log level in production
  log_level: warn
  
  # Enable audit logging in production
  audit_log:
    enabled: true
  
  # Transaction tracer settings
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.5
  
  # Error collector settings
  error_collector:
    enabled: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound" 